
services:
  - type: web
    name: odoo-web
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: odoo-db
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        value: odoo
databases:
  - name: odoo-db
    plan: free
